[package]
name = "gopenpgp-sys"
version = "0.2.18"
edition.workspace = true
license = "MIT"
license-file = "LICENSE"
authors.workspace = true

[dependencies]
base64 = { workspace = true }
hex = { workspace = true }
zeroize = { workspace = true }

[build-dependencies]
bindgen = "0.71"
